### PR TITLE
Update config to reflect new schema in office_hours module. See https…

### PR DESCRIPTION
**Pull request by finnlewis**
…://git.drupalcode.org/project/office_hours/-/blob/8.x-1.4/config/schema/office_hours.schema.yml#L29

### CODE REVIEW

**Comment by finnlewis** [comment]
@ekes @stephen-cox this is now passing the standard tests. 

But it is failing the LocalGovUpdate tests. 

```

There was 1 failure:

1) Drupal\Tests\localgov\Functional\LocalGovUpdateTest::testUpdate
There should be no errors in configuration 'field.storage.paragraph.localgov_contact_office_hours'. Errors:
Schema key field.storage.paragraph.localgov_contact_office_hours:settings.comment failed with: variable type is boolean but applied schema class is Drupal\Core\TypedData\Plugin\DataType\IntegerData

Failed asserting that Array &0 (
    'field.storage.paragraph.localgov_contact_office_hours:settings.comment' => 'variable type is boolean but applied schema class is Drupal\Core\TypedData\Plugin\DataType\IntegerData'
) is true.
```
Is this because the live configuration is not updated by the office_hours module since the Drupal updates?

I've posted an issue here: https://www.drupal.org/project/office_hours/issues/3218789

Maybe I'm getting the wrong end of the stick?

**Comment by finnlewis** [comment]
Note: Thunder have a list of configuration items that the explicitly skip checks on :

https://github.com/thunder/thunder-distribution/blob/6.1.x/tests/src/Functional/Thunder2UpdateTest.php#L27

https://github.com/thunder/thunder-distribution/blob/6.1.x/tests/src/Functional/Thunder2UpdateTest.php#L65

I guess this would be a good way to push past annoying schema check issues.

**Comment by finnlewis** [comment]
This seems to have worked!

I've created a merge request on the original drupal.org module, here: 

https://git.drupalcode.org/project/office_hours/-/merge_requests/3/diffs

which I recall allows us to generate a patch file by apending .patch 

https://git.drupalcode.org/project/office_hours/-/merge_requests/3/diffs.patch

So added that to our pull request here for now. 

https://github.com/localgovdrupal/localgov_paragraphs/pull/33/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R34

This hook_update seems to make the config schema happy for our upgrade tests. 

Let's merge and release this quickly and see if this fixes https://github.com/localgovdrupal/localgov_core/pull/91

**Comment by Adnan-cds** [comment]
> I've created a merge request on the original drupal.org module, here: https://git.drupalcode.org/project/office_hours/-/merge_requests/3/diffs

Hi Finn, I have one small reservation.  The update hook is going to save **each and every** field storage config which may not be desirable.  If we call ```$field->save(TRUE);``` from line 76 only when $field->set() has been called in line 69 or 72, then I should be able to sleep happily :)

**Comment by stephen-cox** [comment]
@finnlewis I agree with Adnan on this. The patch should be updated so that `$field->save(TRUE);` is only called when there have been changes to the field config. 

All tests are currently failing because of this issue so would be good to get this PR approved ASAP. Let me know if you would like a hand with this.

**Comment by finnlewis** [comment]
Yep - thanks @Adnan-cds  and @stephen-cox  - done: 
https://git.drupalcode.org/project/office_hours/-/merge_requests/3/diffs?commit_id=5fcfec8748988da19a45bb4917ae2198ef118c11

**Comment by finnlewis** [comment]
Just re-running the tests to double check... then please approve!

**Comment by finnlewis** [comment]
@stephen-cox @Adnan-cds tests pass - could one of you approve please?

**Review by stephen-cox — APPROVED** [review]
Happy to approve

**Pull request merged**
