### PR TITLE
Initial config and docs for shared paragraphs

### PR DESCRIPTION
**Pull request by stephen-cox**

### CODE REVIEW

**Comment by stephen-cox** [comment]
@finn This is ready for review now.

If you checkout localgov_project on branch feature/32-core-paragraphs you _should_ be able to just `composer update` to get everything, but I had troubles with this. I ended up deleting the `web/modules` and `web/profiles` dirs and then `composer update --no-cache`. This seemed to force composer to find the correct and latest versions of everything.

There are tests, but to run them you need to disable schema checking, which then produces coding standards errors. This is documented here: https://github.com/localgovdrupal/localgov/issues/43.

**Comment by finnlewis** [comment]
Hi @stephen-cox 

I've added a patch for geolocation module which I think fixes the schema issue. The tests do now run.
Can you test?
To get the module to patch properly, I had to remove the modules/contrib folder and re-run composer update from the overall project root.

**Comment by ekes** [comment]
This needs a PR for https://github.com/localgovdrupal/localgov_project/blob/master/composer.json as well to add `"cweagans/composer-patches": "^1.6"` to the require and `"enable-patching": true` to the extra.

**Comment by ekes** [comment]
> This needs a PR for https://github.com/localgovdrupal/localgov_project/blob/master/composer.json as well to add `"cweagans/composer-patches": "^1.6"` to the require and `"enable-patching": true` to the extra.

I've put it in my services testing branch - focusing there at this moment so no separate patch sorry - and it gets a +1 from me from the perspective that localgov_services are installing and phpunit is checking schema again without complaining about paragraphs.

**Comment by stephen-cox** [comment]
@finnlewis Looks good to me. I've made a couple of changes; removed '$strictConfigSchema = FALSE;' from tests and added issue number to composer patch descriptions so it's easier track them later on.

**Pull request merged**
