### PR TITLE
sets leaflet as map provider for contact component

### LINKED ISSUE #177: Switch map in contact component from Google to Open Street Map
Councils are reporting issues with Google Maps in the contact component. Anecdotally some have made a switch to OSM themselves.

We're using OSM elsewhere so this is possibly the last LGD use of Google Maps.

We ought to switch this over so no future councils have to do this unnecessary work.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #177 

Some of the formatting in this is just Drupal rearranging the order of items in the YML file, I think we should leave this new formatting in place as it's how Drupal wants the formatting to appear.

After that there's a big block of green which is the actual code change to stop using Google maps and use leaflet/OSM instead.

### CODE REVIEW

**Comment by finnlewis** [comment]
Looks like the tests are failing, and we can't see why on Github as paratest is being mean.

Let's check the tests locally.

**Comment by markconroy** [comment]
@finnlewis can you run these tests locally? I'm trying to, but the only error I am getting is that the config should be in alphabetical order (on all the files except the ones I am working on).

**Comment by stephen-cox** [comment]
@markconroy I have run the tests on my local computer and it looks like there's problem with the `core.entity_view_display.paragraph.localgov_contact.default` config.


Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.paragraph.localgov_contact.default with the following errors: core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.third_party_settings.field_formatter_class missing schema

and

Exception: Exception when installing config for module localgov_paragraphs, message was: Schema errors for core.entity_view_display.paragraph.localgov_contact.default with the following errors: core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_rotate.settings.display_control missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_rotate.settings.bearing missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_attribution.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_attribution.settings.prefix missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_fullscreen.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_geocoder.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_geocoder.settings.geocoder missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_geocoder.settings.settings missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_locate.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_recenter.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_scale.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_scale.settings.metric missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_scale.settings.imperial missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_layer.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_layer.settings.default_label missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_layer.settings.tile_layer_providers missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_layer.settings.tile_providers_options missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_control_zoom.settings.position missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_clusterer.settings.cluster_settings missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_clusterer.settings.disable_clustering_at_zoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_clusterer.settings.custom_marker_settings missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.marker_shadow_path missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.marker_icon_path missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.icon_size missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.icon_anchor missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.popup_anchor missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.shadow_size missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_icon.settings.shadow_anchor missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.info_auto_display missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.max_width missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.min_width missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.max_height missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.auto_pan missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.keep_in_view missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.close_button missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.auto_close missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.close_on_escape_key missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_popup.settings.class_name missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_marker_zoom_and_animate.settings.marker_zoom_anchor_id missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_max_bounds.settings.north missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_max_bounds.settings.south missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_max_bounds.settings.east missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_max_bounds.settings.west missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_custom_tile_layer.settings.tile_layer_url missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_custom_tile_layer.settings.tile_layer_attribution missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_custom_tile_layer.settings.tile_layer_subdomains missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_custom_tile_layer.settings.tile_layer_zoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_tile_layer_overlay.settings.tile_layer_overlay missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_tile_layer.settings.tile_layer_provider missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_tile_layer.settings.tile_provider_options missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.url missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.version missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.layers missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.styles missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.srs missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.format missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.transparent missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.map_features.leaflet_wms.settings.identify missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.zoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.height missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.width missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.minZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.maxZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.maxBounds missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.crs missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.preferCanvas missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.zoomSnap missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.zoomDelta missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.trackResize missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.boxZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.doubleClickZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.dragging missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.zoomAnimation missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.zoomAnimationThreshold missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.fadeAnimation missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.markerZoomAnimation missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.inertia missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.inertiaDeceleration missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.easeLinearity missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.worldCopyJump missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.maxBoundsViscosity missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.keyboard missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.keyboardPanDelta missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.scrollWheelZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.wheelDebounceTime missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.wheelPxPerZoomLevel missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.tap missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.tapTolerance missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.touchZoom missing schema, core.entity_view_display.paragraph.localgov_contact.default:content.localgov_contact_location.settings.map_provider_settings.bounceAtZoomLimits missing schema

**Comment by markconroy** [comment]
Thanks @stephen-cox.

That's a bit strange, as it all installs fine and seems to work as expected. And the config that we have is just want Drupal output from a config export, so not sure why it's not validating.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by markconroy** [comment]
I've updated/re-exported the config file for the display of the contact paragraph type, but looks like we are still getting the config schema issue. I've no idea why, especially since this is a config file exported from Drupal rather than hand-coded by us.

Is this a false negative/positive?

**Pull request merged**
