### PR TITLE
Restore attributes on banner paragraphs

### PR DESCRIPTION
**Pull request by graham-web**
Fix banner paragraphs disappearing when edited in Layout Paragraphs 2.x

### CODE REVIEW

**Comment by finnlewis** [comment]
Thanks @graham-web 

I'd like @markconroy and/or @msayoung to take a look at this for awareness and review if possible. Might we want any corresponding changes in the localgov_base theme for example?

**Comment by markconroy** [comment]
This is not an issue in localgov_base. However, in this PR we are removing the `bg-white` class, which I am not sure we want to do (without discussion).

I think this PR should only add in the attributes and nothing else. so changing `<div class="bg-white">` to `<div{{ attributes.addClass('bg-white')>`

**Comment by finnlewis** [comment]
@graham-web did you see  the reply from @markconroy above? Thoughts?

**Comment by markconroy** [comment]
Sorry, I made a mistake on this. The bg-white is now added in the classes array, so all is fine.

**Review by markconroy — APPROVED** [review]

**Pull request merged**
