### PR TITLE
Create a heading from the heading level and text field, as per localg…

### PR DESCRIPTION
**Pull request by msayoung**
…ov_subsites_paragraphs

### CODE REVIEW

**Comment by markconroy** [comment]
I'm getting an error when I install this

```User warning: The following theme is missing from the file system: localgov_paragraphs_views in Drupal\Core\Extension\ExtensionPathResolver->getPathname() (line 63 of core/lib/Drupal/Core/Extension/ExtensionPathResolver.php).

Drupal\Core\Extension\ExtensionPathResolver->getPathname('theme', 'localgov_paragraphs_views
') (Line: 85)```

Seems there is no libary called `localgov_paragraphs_views`, so we should probably remove 
``` $variables['#attached']['library'][] = 'localgov_paragraphs_views
/localgov_paragraphs_views
';
```

The heading level also does not seem to be getting applied, as well as the field label "Heading Level" being visible.

Screenshot 2022-10-10 at 14 42 26

**Comment by msayoung** [comment]
@markconroy do you have this? 
 https://github.com/localgovdrupal/localgov_base/pull/289

**Comment by markconroy** [comment]
Ah, thanks. The heading level is working now, but we still have

- calling a library (that it thinks is from a theme) that doesn't exist, and
- 'Heading level' field still being visible.

Screenshot 2022-10-10 at 14 59 00

**Comment by msayoung** [comment]
> * 'Heading level' field still being visible.

hidden in: https://github.com/localgovdrupal/localgov_base/pull/297

**Review by markconroy — APPROVED** [review]

**Pull request merged**
