### PR TITLE
Releasing test base class adjustment

### PR DESCRIPTION
**Pull request by Adnan-cds**
[ParagraphsTestBase](https://git.drupalcode.org/project/paragraphs/-/blob/8.x-1.x/tests/src/Functional/WidgetLegacy/ParagraphsTestBase.php) class file has moved into a new directory/namespace which is breaking test runs.

### CODE REVIEW

**Review by finnlewis — CHANGES_REQUESTED** [review]
Discussing in the Merge Monday meeting, @Adnan-cds has reviewed the hook_update that this adds (from last August) and thinks this is no longer necessary. 

This comes from : https://www.drupal.org/project/drupal/issues/3223319

The core issue has since been resolved (4 months ago), so we can get rid of the hook_update and avoid changing people's config.

**Comment by Adnan-cds** [comment]
Ready for review :)

**Review by finnlewis — APPROVED** [review]
Discussed in Merge Monday meeting - no objections to merging.

**Comment by Adnan-cds** [comment]
Thanks.  Merging...

**Pull request merged**
