### PR TITLE
Adds update hook to ensure localgov_numbered_text paragraph is available.

### PR DESCRIPTION
**Pull request by rupertj**
Fix for #161

### CODE REVIEW

**Comment by rupertj** [comment]
There's currently two failures: One's a deprecation which I've made an issue for (#163) and one seems to be an unrelated failure to run the tests in general?

**Comment by rupertj** [comment]
The unrelated failure on the unit tests seems to be caused by Paratest.

I've seen the same error on localgov_publicatons, and swopping the call to Paratest to a call to PHPUnit directly fixes the issue.

EG:
Failing with Paratest: https://github.com/localgovdrupal/localgov_publications/actions/runs/7430426055
Passing with PHPUnit: https://github.com/localgovdrupal/localgov_publications/actions/runs/7430496585

The only difference between those two runs is this commit: https://github.com/localgovdrupal/localgov_publications/commit/491aef4e82336018ebc6ca6622e3d14e2ff8bd6d

**Comment by andybroomfield** [comment]
Have installed and run the update on a site that already has localgov paragraphs installed

Screenshot 2024-01-09 at 2 34 41 pm

Now see Numbered paragraphs as a valid paragraph type

Screenshot 2024-01-09 at 2 34 28 pm

**Comment by andybroomfield** [comment]
And I've checked this with a modified numbered paragraphs field and re-running the update and it wasn't removed so this should be good to go.

**Review by andybroomfield — APPROVED** [review]

**Comment by stephen-cox** [comment]
Fix for the code deprecation here: #166 
Fix for the PHPUnit tests here: #165 

As @andybroomfield is happy with this I think we're good to merge

**Pull request merged**
