### PR TITLE
Temporary fix for Contact paragraph add/edit form

### LINKED ISSUE #40: Can't add/edit Contact paragraph
@see https://github.com/localgovdrupal/localgov_page_components/issues/22

[Dan has pointed out](https://github.com/localgovdrupal/localgov_page_components/issues/22#issuecomment-902539788) that this is due to a [core bug](https://www.drupal.org/project/drupal/issues/3223319).  Using horizontal tabs instead of vertical tabs in the Contact paragraph form avoids the issue.  The proposed change for the core bug has not been discussed enough.  For that reason, I am opting to switch to horizontal tabs for now.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Contact Paragraph's form display should use horizontal tabs instead of vertical tabs.  These tabs are provided by the field_group module.

This is a temporary work around for a Drupal 9.x core bug involving the Claro theme.
@see https://www.drupal.org/project/drupal/issues/3223319

Resolves #40

### CODE REVIEW

**Review by danchamp — COMMENTED** [review]
@Adnan-cds Tested and the update hook fires as expected and updates the tab  configuration.

I tested updates in the UI as well and the formatting of the success message is off:

Screenshot 2021-08-26 at 17 55 29

Which is a pity because the magenta worked well in the terminal.

**Comment by Adnan-cds** [comment]
Thanks Dan.  I have removed the coloured text from the browser output.  Please try again.

**Comment by danchamp** [comment]
All good now @Adnan-cds, happy to approve thanks.

**Comment by Adnan-cds** [comment]
Thanks Dan.  Merging...

**Pull request merged**
