### PR TITLE
Removed call to deprecated format_size()

### LINKED ISSUE #163: Deprecation error in CI
See here: https://github.com/localgovdrupal/localgov_paragraphs/actions/runs/7426621431/job/20210755941

```
Error: Call to deprecated function format_size():
in drupal:10.2.0 and is removed from drupal:11.0.0. Use
  \Drupal\Core\StringTranslation\ByteSizeMarkup::create($size, $langcode)
  instead.
 ------ -------------------------------------------------------------------------- 
  Line   modules/localgov_subsites_paragraphs/localgov_subsites_paragraphs.module  
 ------ -------------------------------------------------------------------------- 
  211    Call to deprecated function format_size():                                
         in drupal:10.2.0 and is removed from drupal:11.0.0. Use                   
           \Drupal\Core\StringTranslation\ByteSizeMarkup::create($size,            
         $langcode)                                                                
           instead.                                                                
 ------ -------------------------------------------------------------------------- 
```

### PR DESCRIPTION
**Pull request by rupertj**
Replaced with Drupal\Core\StringTranslation\ByteSizeMarkup::create() as per https://www.drupal.org/node/2999981.

Fixes #163.

### CODE REVIEW

**Comment by andybroomfield** [comment]
As noted on the issue ByteSizeMarkup class was introduced in Drupal 10.2 so we would need to hold on this until we can set 10.2 as the minimum supported version (when 10.3 is released).

**Comment by finnlewis** [comment]
Looking at 17th June 2024 for 10.3.0 to be released and 10.1.x to end security support.

**Comment by stephen-cox** [comment]
@ekes points out that it's possible to check the version of Drupal can call different functions depending on the version. Should be useful in this case.

See https://mglaman.dev/blog/writing-backward-compatible-deprecation-fixes-contributed-modules-will-be-much-easier-drupal

**Comment by finnlewis** [comment]
Some merge conflict to be resolved.

After that, what shall we do with this @rupertj ? Hang tight like @andybroomfield suggests or write something to check the version like @stephen-cox mentions?

**Comment by markconroy** [comment]
Drupal 10.3 is out now. Can we set Drupal 10.2 as our minimum supported version, and merge this?

**Review by stephen-cox — APPROVED** [review]

**Pull request merged**
