### PR TITLE
Localgov paragraphs accordion enhancements

### PR DESCRIPTION
**Pull request by ctorgalson**
## What does this change?

This is in response to [a feature request](https://github.com/localgovdrupal/localgov/issues/653) regarding two additional capabilities for the `localgov_paragraphs` module:

1. the ability to configure an instance of the paragraph to allow more than one simultaneously expanded pane
2. the ability to configure an instance of the paragraph to use a button to show or hide all panes simultaneously (like the Step by Step sidebar does)

To do this, I've made the following changes to the module:

### Fields

- add boolean field 'localgov_allow_multiple_open` to the paragraph type
- add boolean field `localgov_display_show_hide_all` to the paragraph type
- add required config files for entity form, entity view, field, and field storage
- add a new `localgov_paragraphs.install` file to add the new fields to existing installs

### Twig

- add a small conditional block containing only a `<button>` element to `paragraph--localgov-accordion.html.twig`

### CSS

- add a single css declaration to `localgov-accordion.css` 

### Javascript

- remove `localgov-accordion.js`
- rename `localgov-accordion.es6.js` to `localgov-accordion.js` (per Technical Drop-in call August 29)
- add various functions to the file, keeping the new logic as independent from the existing functionality as possible

## How to test

All tests to be done on this branch, at e.g. `/fostering/types-fostering`:

### Default: succeeds if accordion behavior matches demo.localgovdrupal.org

1. edit the paragraph
2. ensure neither "Allow Multiple Open" nor "Show Hide All" field is checked
3. save the paragraph and node
4. use the accordion normally

### "Allow Multiple Open": succeeds if multiple panes can be simultaneously opened

1. edit the paragraph
2. check the "Allow Multiple Open" field
3. save the paragraph and node
4. on the FE, click to open one pane
5. on the FE, click to open another pane

### "Show/Hide all" 1: succeeds when each button click has the expected result

1. edit the paragraph
2. check the "Show HIde All" field
3. un-check the "Allow Multiple Open" field
4. save the paragraph and node
5. on the FE, verify that the "Show all Sections" button is available
6. click the button to show all sections
7. click the button again to hide all sections

### "Show/Hide all" 2: succeeds when the "Show all Sections" button self-updates and behavior matches label

1. refresh the page with "Show all Sections" enabled
2. without clicking "Show all Sections", click open each closed accordion pane
3. click the button whose label should have changed to "Hide all Sections"

### "Show/Hide all" 3: succeeds when the "Show all Sections" button self-updates and behavior matches label

1. refresh the page with "Show all Sections" enabled
2. click the "Show all Sections" button
3. close each open accordion pane
4. click the button shows label should have changed to "Show all Sections"

### "Show/Hide all" 4: succeeds when the behavior exactly matches 1, 2, and 3

(Setting Show/Hide All _implies_ "Allow Multiple" so checking both fields should exactly match the previous three tests.

1. edit the paragraph
2. check the "Show HIde All" field
3. check the "Allow Multiple Open" field
4. save the paragraph and node
5. test as per "Show/Hide all" 1, 2, and 3. 

## How can we measure success?

Pass the manual tests above.

## Have we considered potential risks?

The risks are principally a11y-related, but somewhat mitigated by the fact that the behavior of this accordion paragraph is an exact match for similar UI constructs used elsewhere in LGD (Step by Steps, e.g.) and [gov.uk](https://design-system.service.gov.uk/components/accordion/).

Having said that, thanks to previous a11y reviews on similar component, I'm skeptical of gov.uk's approach that LGD follows. See "Accessibility" below for details.

### Before

image

### After (only when Show/Hide All is enabled)

image 

## Accessibility

So I'm satisfied that these changes pass the tests below in the same way that LGD's and gov.uk's other accordions do (in fact, [it's one notch better than step-by-step's](https://github.com/localgovdrupal/localgov_step_by_step/issues/111) in terms of predictability.

What I'm _not_ confident about is that the use of a `<button>` element with an `aria-expanded` attribute is correct for this behaviour.

After accessibility review for an almost identical component developed elsewhere, we modified the component to use a `<button>` _without_ an `aria-expanded` attribute (though still correctly labelled) and `Drupal.announce()` to speak a message for screenreader users saying something like "expanded all panes", or "collapsed all panes".

I guess I would just like a tie-breaking accessibility evaluation before we merge this.

-   [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [x] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [x] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Comment by markconroy** [comment]
Thanks a lot for this @ctorgalson, it's working very well.

Two things I noticed from my testing.

1. I'd prefer if the booleans were at the top of the form rather than the bottom, and
2. You can't have "Allow multiple open" _and_ "Show expand all" buttons both checked. 

For number 2, the `if` statement in the code has an `elseif` which means only one of these buttons can be present at one time. Maybe we should change it to 2 `if` statements instead.

```
{% if paragraph.localgov_allow_multiple_open.value == 1 %}
  {% set attributes = attributes.setAttribute('data-accordion-allow-multiple', '') %}
{% elseif paragraph.localgov_display_show_hide_all.value == 1 %}
  {% set attributes = attributes.setAttribute('data-accordion-display-show-hide', '') %}
{% endif %}
```

**Comment by ctorgalson** [comment]
Thanks @markconroy.

I'll swap (1).

For (2), I agree it's not super-evident from the code, but as I've noted [in the Display Show/Hide All field description](https://github.com/localgovdrupal/localgov_step_by_step/issues/111), and [hinted at in the js itself](https://github.com/localgovdrupal/localgov_paragraphs/pull/192/files#diff-729bd20df0dc89e529e752e2d9bdf09073e4c358ed8b7285c731e3edbd8f63e9R106) (where `allowMultiple` is set to `true` whenever `displayShowHide` is `true`), enabling "Display Show/Hide All" _already_ enables both.

From the field description:

> When checked, the resulting accordion will include a button allowing all panes to be open or closed at once. Note that this automatically enables the option to open multiple panes at once.

Changing the Twig to use two `if` statements would only output an additional data attribute that would never be used in the js.

---

Added: I would have made the one checkbox auto-check the other in the paragraphs edit form, but it seemed like too much messing around compared to using the description.

**Comment by markconroy** [comment]
I don't think that makes sense. At a minimum, after checking "show show all button" I'd expect a button to "Show all". 

I also don't think having that button should automatically mean we activate the "allow" multiple feature.

**Comment by ctorgalson** [comment]
Not sure I understand this:

> I don't think that makes sense. At a minimum, after checking "show show all button" I'd expect a button to "Show all".

That is what happens (isn't it? are you seeing something _else_ happen?)

> I also don't think having that button should automatically mean we activate the "allow" multiple feature.

I can't envison a non-confusing UI for that. E.g, what should happen if:

- show/hide all **is** enabled
- allow multiple **is not** enabled
- the user clicks "Show All"
- the user clicks one of the accordion items

There are two alternatives:

1. _only_ the clicked item closes (this is the current behaviour)
2. _all_ the open items close (for myself at least, I'd be pretty suprised by that)

**Comment by markconroy** [comment]
Here's what I am seeing:

Both checkboxes are checked:

Screenshot 2024-09-02 at 11 40 44

But there is no "Show/Hide all".


Screenshot 2024-09-02 at 11 40 54

When only "Show/Hide all" is checked, I see the button.

Screenshot 2024-09-02 at 11 42 24

**Comment by ctorgalson** [comment]
Aha--that's a bug for sure. Thanks!

**Comment by ctorgalson** [comment]
@markconroy I've fixed the missing "Show all sections" button, and tweaked the the relevant config file and `hook_install_N()` implementation to place the fields at the top of the form, just after the title.

**Review by markconroy — APPROVED** [review]
This looks good to me. Thanks.

**Comment by ekes** [comment]
MT: We'll double check the update created config gets UUIDs.

For the rest ready to merge.

**Comment by ctorgalson** [comment]
Looks like the created config (`field.storage.paragaraph.${fieldName}.yml` and `field.field.paragraph.localgov_accordion.${fieldName}.yml` _do_ get uuids on update.

Tested by:

1. fresh `composer` install of lgd codebase with `2.x` branch of `localgov_paragraphs` checked out
2. checkout this (mis-named) branch, `2024_w35_localgov_paragraphs_accordion_enhancements`
3. run `drush updb -y`
4. run `drush cex -y`
5. check `field.storage.paragaraph.${fieldName}.yml` and `field.field.paragraph.localgov_accordion.${fieldName}.yml` for uuids

Still wouldn't hurt for somebody else to check my work :D

**Comment by ekes** [comment]
> Still wouldn't hurt for somebody else to check my work :D

Confirmed. I got UUIDs.

If I was to nit-pick we should actually include the configuration being created here in the update hook. It's kinda Drupal best practice not to rely on anything external to an update hook. Logic being that the code outside the update hook can change, and you don't know when the hook is going to be run. In this case I suspect it's not so important.

**Comment by ctorgalson** [comment]
@ekes I think I can fix that up. I imitated the parent module, but it's not a lot of config to change.

**Comment by ctorgalson** [comment]
Swapped yaml config for literal config in the `hook_update_N()` implementation if anyone would like to re-test (should work: only the _sources_ of the config values have changed, not the values themselves).

Works for me on a fresh install using `localgov_paragraphs` 2.x.

**Pull request merged**
