### PR TITLE
Add dependency on Layout Paragraphs 2

### LINKED ISSUE #57: Layout Paragraphs 2.x
The newer version of layout paragraphs looks good. 

https://www.drupal.org/project/layout_paragraphs/releases/2.0.0-beta1

Better UX and more configurable modal behaviour. 

I'm just taking it for a spin locally. 

Some nice improvements include:

### Clearer links to add section and add paragraphs: 

image

### Better (legible) list of paragraph type: 

image

### LINKED ISSUE #79: Check dependency chain for layout_paragraphs
Looks like we don't have a dependency on layout_paragraphs in composer.json 

https://github.com/localgovdrupal/localgov_paragraphs/blob/2.x/composer.json#L8

We should check this and add.

Note: we are also looking at upping to 2.x branch of layout_paragraphs: 

https://github.com/localgovdrupal/localgov_subsites/pull/85

### PR DESCRIPTION
**Pull request by stephen-cox**
Upgrade to Layout Paragraphs 2. Adding new dependency here to sort out the dependencies in Page and Subites.

Fixes #79

Also see:

See also:
- https://github.com/localgovdrupal/localgov_subsites/pull/85
- https://github.com/localgovdrupal/localgov_subsites/pull/109
- https://github.com/localgovdrupal/localgov_page/pull/38
- https://github.com/localgovdrupal/localgov_microsites/issues/84

### CODE REVIEW

**Comment by stephen-cox** [comment]
There are 3 pull requests that will upgrade Layout Paragraphs to version 2.

- https://github.com/localgovdrupal/localgov_paragraphs/pull/83 - Add dependency on Layout Paragraphs 2
- https://github.com/localgovdrupal/localgov_page/pull/38 - Remove dependency on Layout Paragraphs
- https://github.com/localgovdrupal/localgov_subsites/pull/109 - Remove dependency on Layout Paragraphs

Anyone wanting to give this a whirl can use the feature/layout-paragraphs-2 branch on [LocalGov Project](https://github.com/localgovdrupal/localgov_project/tree/feature/layout-paragraphs-2). There's a PR to test everything here: https://github.com/localgovdrupal/localgov_project/pull/91

It's been suggested that t[hese are released as major version updates](https://github.com/localgovdrupal/localgov_subsites/pull/85#issuecomment-1260737202); Paragraphs 3.0.0 and Subsites 3.0.0, Page is still dev. My suggestion is we do minor version updates and update the dependency in Page and Subsites to require the new minor version of Paragraphs; so Paragraphs 2.2.0 with Subsites 2.2.0 requiring localgovdrupal/localgov_paragraphs:^2.2.

**Review by finnlewis — APPROVED** [review]
Yes! Makes sense, thanks @stephen-cox

**Comment by finnlewis** [comment]
On the major versus minor releases, I'm comfortable with minor point releases. I don't think we're introducing any incompatible API changes with this.

**Comment by finnlewis** [comment]
Hey @stephen-cox 

I've tested this locally with the https://github.com/localgovdrupal/localgov_project/tree/feature/layout-paragraphs-2 branch.

Fresh install, enabled demo content, everything looks fine and I can edit the subsites paragraphs. 

I'll test with a microsites install too.

**Comment by andybroomfield** [comment]
How about?
`"drupal/layout_paragraphs": "^1.0 || ^2.0",`
Is there anything that needs to be changed in config that is incompatible?

**Comment by finnlewis** [comment]
I also tested this lcoally on a localgov_microsites install and it worked well.

**Comment by stephen-cox** [comment]
> How about? `"drupal/layout_paragraphs": "^1.0 || ^2.0",` Is there anything that needs to be changed in config that is incompatible?

Unfortunately, there are schema changes. They are very minor, but enough for tests to fail. See https://github.com/localgovdrupal/localgov_directories/pull/234

**Comment by finnlewis** [comment]
Discussing the release in Merge Monday meeting.

Steps: 
1. merge this one first.
2. Then go to localgov_subsites and bump the version of locagov_paragraphs and do a release. 
3. then move on to directories 

Discussion on versions: 

Bump localgov_paragraphs to 2.1.2 to 2.2.0 or to 3.0.0 ?
Bump localgov_subsites to 2.2.0 to 2.3.0 or to 3.0.0 ?

@andybroomfield would like for it to be easy to avoid upgrading immediately to be able to communicate it to content designers. So preferred a major version bump. 
However, this would also mean bumping  the profile by a major version, which seems like overkill.

So: suggestion is to 

1. Bump localgov_paragraphs to 2.1.2 to 2.2.0 
2. Bump localgov_subsites to 2.2.0 to 2.3.0
3. Add release notes to highlight that this now depends on layout_paragraphs 2.x, and to avoid upgrading to this you can pin localgov_paragraphs to 2.1.2 and localgov_subsites to 2.2.0 in your root composer.json.

**Pull request merged**
