### PR TITLE
Remove microsite views from paragraph config

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
I've removed the microsite views from the config. I wonder whether we would like to create some default views to reference - if so what? 
Given we can't assume any of the sub-modules (events, news etc) what would be useful ?

Equally we could create some useful views to be referenced in each of those modules and update the config here automagically. 

Thoughts @finnlewis @stephen-cox  (not sure who else was involved in this discussion at Merge Monday)

**Review by stephen-cox — APPROVED** [review]
I think this is fine for now. We can think of the sort of views that will be useful later on

**Comment by Adnan-cds** [comment]
I don't understand this change as I am not involved in Microsites but I am happy as long as Steve is happy :)

**Review by finnlewis — APPROVED** [review]
From discussion, this looks good to go @msayoung

**Pull request merged**
