### PR TITLE
Enable media_library_edit so that image fields can be edited again a…

### PR DESCRIPTION
**Pull request by msayoung**
…fter upload

### CODE REVIEW

**Comment by msayoung** [comment]
Requires https://github.com/localgovdrupal/localgov_core/pull/146 to be released before tests will pass

**Comment by finnlewis** [comment]
From discussion at Merge Monday: 
@ekes explains that we need third party settings defined in the config schema of the source module. 

For example, see: https://git.drupalcode.org/project/crop/-/blob/8.x-2.x/config/schema/crop.schema.yml

So this will need a patch to https://git.drupalcode.org/project/media_library_edit/-/tree/8.x-2.x module as it currently does not define schema.

**Comment by finnlewis** [comment]
Looking at this locally now

**Comment by finnlewis** [comment]
@stephen-cox @ekes I'm not really making much progress on this.

Here's what I'm trying 
https://git.drupalcode.org/issue/media_library_edit-3315757/-/blob/3315757-thirdpartysettings.medialibraryedit-missing-schema/config/schema/media_library_edit.schema.yml

I've tried a few different permutations but nothing seems to help. 

I'm using this test to test: 
```
phpunit web/modules/contrib/localgov_paragraphs/tests/src/Functional/ --filter=testContactPageComponentEditPage
```
And getting
```
1) Drupal\Tests\localgov_paragraphs\Functional\ContactEditTest::testContactPageComponentEditPage
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_form_display.paragraph.localgov_image.default with the following errors: core.entity_form_display.paragraph.localgov_image.default:content.localgov_image.third_party_settings.media_library_edit missing schema
```

This is perhaps useful@ https://www.drupal.org/project/field_group/issues/3090462#comment-13360417

This also: https://git.drupalcode.org/project/display_machine_name/-/blob/2.x/config/schema/display_machine_name.schema.yml

**Comment by finnlewis** [comment]
Maybe try this: 

```
/**
   * Skip schema check for config defining leaflet_formatter_default settings.
   *
   * @var string[]
   */
  protected static $configSchemaCheckerExclusions = [
    'core.entity_view_display.localgov_geo.address.default',
    'core.entity_view_display.localgov_geo.address.embed',
    'core.entity_view_display.localgov_geo.address.full',
  ];

**Review by finnlewis — APPROVED** [review]
OKAY! The tests now pass (after excluding most paragraph entity forms from the schema checks) so let's get this baby merged. Thanks @msayoung !

**Pull request merged**
